version: '2'
volumes:
  gnupg:
  ssh:
  password-store:
  maroonalpha:
  cloud9:
services:
  volume-master:
    image: emorymerryman/cloud9:0.0.1
    ports:
      - "8080"
    volumes:
      - gnupg:/srv/gnupg
      - ssh:/srv/ssh
      - password-store:/srv/password-store
      - maroonalpha:/srv/maroonalpha
      - cloud9:/srv/cloud9
  personal:
    image: emorymerryman/cloud9:0.0.1
    ports:
      - "8080"
    volumes:
      - gnupg:/root/.gnupg
      - ssh:/root/.ssh
  maroonalpha:
    image: emorymerryman/cloud9:0.0.1
    ports:
      - "8080"
    volumes:
      - gnupg:/root/.gnupg
      - ssh:/root/.ssh
      - maroonalpha:/maroonalpha
    command: --listen 0.0.0.0 -p 8080 -w /maroonalpha --auth user:password
  cloud9:
    image: emorymerryman/cloud9:0.0.1
    volumes:
      - gnupg:/root/.gnupg
      - ssh:/root/.ssh
      - cloud9:/cloud9
    command: --listen 0.0.0.0 -p 8080 -w /cloud9 --auth user:password
