version: '2'
volumes:
  personal:
  bin:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  maroonalpha:
  cloud9:
  deciphernow:
  send-data-volumes:
services:
  personal:
    build: dockers/personal
    ports:
      - "8080"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - personal:/root
    links:
      - gitlab
  bin:
    image: emorymerryman/cloud9:0.0.1
    ports:
      - "8080"
    volumes:
      - personal:/root
      - bin:/workspace/bin
    command: --listen 0.0.0.0 -p 8080 -w /workspace/bin --auth user:password
  gitlab:
    image: gitlab/gitlab-ce:8.10.4-ce.0
    ports:
      - "443"
      - "80"
      - "22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
  maroonalpha:
    build: dockers/maroonalpha
    ports:
      - "8080"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - personal:/root
      - maroonalpha:/workspace/maroonalpha
    links:
      - gitlab
    command: --listen 0.0.0.0 -p 8080 -w /workspace/maroonalpha --auth user:password
  receiver:
    build: dockers/receiver
    ports:
     - "22"
    volumes:
      - personal:/volumes/personal
      - bin:/volumes/bin
      - gitlab_config:/volumes/gitlab_config
      - gitlab_logs:/volumes/gitlab_logs
      - maroonalpha:/volumes/maroonalpha
      - cloud9:/volumes/cloud9
      - deciphernow:/volumes/deciphernow
      - send-data-volumes:/volumes/send-data/volumes
  send-data-volumes:
    build: dockers/send-data-volumes
    ports:
      - "8080"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - personal:/root
      - send-data-volumes:/workspace/send-data-volumes
    links:
      - gitlab
  cloud9:
    image: emorymerryman/cloud9:0.0.1
    volumes:
      - personal:/root
      - cloud9:/workspace/cloud9
    links:
      - gitlab
    command: --listen 0.0.0.0 -p 8080 -w /workspace/cloud9 --auth user:password
  deciphernow:
    build: dockers/deciphernow
    ports:
      - "8080"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - deciphernow:/root
    links:
      - gitlab
    
